/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author ACER
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        excaBT = new javax.swing.JButton();
        loaderBT = new javax.swing.JButton();
        graderBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        graderLabel = new javax.swing.JLabel();
        excaLabel = new javax.swing.JLabel();
        loaderLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        buttonPanel.setBackground(new java.awt.Color(255, 255, 153));
        buttonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        excaBT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        excaBT.setText("Excavator");
        excaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(excaBT);

        loaderBT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loaderBT.setText("Loader");
        loaderBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaderBTActionPerformed(evt);
            }
        });
        buttonPanel.add(loaderBT);

        graderBT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        graderBT.setText("Grader");
        graderBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graderBTActionPerformed(evt);
            }
        });
        buttonPanel.add(graderBT);

        exitBT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        exitBT.setText("Keluar");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        buttonPanel.add(exitBT);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 153)));
        imagePanel.setLayout(new java.awt.CardLayout());

        graderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Grader.jpg"))); // NOI18N
        imagePanel.add(graderLabel, "2");

        excaLabel.setBackground(new java.awt.Color(102, 255, 204));
        excaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Excavator.jpg"))); // NOI18N
        excaLabel.setMaximumSize(new java.awt.Dimension(316, 400));
        excaLabel.setMinimumSize(new java.awt.Dimension(316, 400));
        imagePanel.add(excaLabel, "0");

        loaderLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/Loader.jpg"))); // NOI18N
        imagePanel.add(loaderLabel, "1");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void graderBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graderBTActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_graderBTActionPerformed

    private void excaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excaBTActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_excaBTActionPerformed

    private void loaderBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaderBTActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_loaderBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
            GraphicsDevice device =
                    GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
            device.setFullScreenWindow(fullFrame);
            
            fullFrame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton excaBT;
    private javax.swing.JLabel excaLabel;
    private javax.swing.JButton exitBT;
    private javax.swing.JButton graderBT;
    private javax.swing.JLabel graderLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton loaderBT;
    private javax.swing.JLabel loaderLabel;
    // End of variables declaration//GEN-END:variables
}
